"""NoteGrab: paste notes, get a multiple-choice quiz generated by Claude."""
import os
import logging

from anthropic import Anthropic, APIError
from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field, ValidationError

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO)

load_dotenv()

MODEL = os.getenv("CLAUDE_MODEL", "claude-sonnet-5-5")
client = Anthropic()  # reads ANTHROPIC_API_KEY from the environment

app = FastAPI(title="NoteGrab API")


# ---------- Schemas ----------
class QuizRequest(BaseModel):
    notes: str = Field(..., min_length=50, max_length=20_000)
    num_questions: int = Field(5, ge=1, le=15)


class Question(BaseModel):
    question: str
    choices: list[str] = Field(..., min_length=4, max_length=4)
    answer_index: int = Field(..., ge=0, le=3)
    explanation: str


class QuizResponse(BaseModel):
    title: str
    questions: list[Question]


QUIZ_TOOL = {
    "name": "submit_quiz",
    "description": "Submit a multiple-choice quiz based on the user's notes.",
    "input_schema": {
        "type": "object",
        "properties": {
            "title": {"type": "string", "description": "Short topic title for the quiz"},
            "questions": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "question": {"type": "string"},
                        "choices": {
                            "type": "array",
                            "items": {"type": "string"},
                            "minItems": 4,
                            "maxItems": 4,
                        },
                        "answer_index": {"type": "integer", "minimum": 0, "maximum": 3},
                        "explanation": {
                            "type": "string",
                            "description": "One or two sentences on why the answer is correct",
                        },
                    },
                    "required": ["question", "choices", "answer_index", "explanation"],
                },
            },
        },
        "required": ["title", "questions"],
    },
}

SYSTEM_PROMPT = (
    "You write study quizzes from a student's notes. Every question must be "
    "answerable from the notes alone. Test understanding, not trivia. Each question "
    "has exactly 4 choices with plausible distractors and one correct answer. "
    "Vary the position of the correct answer. "
    "Always respond by calling the submit_quiz tool. Do not reply with plain text."
)


# ---------- Routes ----------
@app.post("/api/quiz", response_model=QuizResponse)
def generate_quiz(req: QuizRequest) -> QuizResponse:
    try:
        msg = client.messages.create(
            model=MODEL,
            max_tokens=8000,
            system=SYSTEM_PROMPT,
            tools=[QUIZ_TOOL],
            # Forced tool_choice ("tool"/"any") is rejected by this model, so use
            # "auto" and rely on the system prompt plus the checks below.
            tool_choice={"type": "auto"},
            messages=[{
                "role": "user",
                "content": f"Write {req.num_questions} questions from these notes:\n\n<notes>\n{req.notes}\n</notes>",
            }],
        )
    except APIError:
        logger.exception("Claude API error")
        raise HTTPException(status_code=502, detail="Claude API error")

    tool_block = next((b for b in msg.content if b.type == "tool_use"), None)
    if tool_block is None:
        logger.error("No tool_use block; stop_reason=%s, types=%s",
                    msg.stop_reason, [b.type for b in msg.content])
        raise HTTPException(status_code=502, detail="Model did not return a quiz.")

    try:
        quiz_response = QuizResponse.model_validate(tool_block.input)
    except ValidationError:
        logger.exception("Quiz failed validation; stop_reason=%s", msg.stop_reason)
        raise HTTPException(status_code=502, detail="Model returned an invalid quiz.")

    if len(quiz_response.questions) != req.num_questions:
        logger.warning("Asked for %d questions, got %d", req.num_questions, len(quiz_response.questions))

    return quiz_response


@app.get("/api/health")
def health():
    return {"status": "ok", "model": MODEL}


# Serve the frontend from the same server (no CORS setup needed)
app.mount("/", StaticFiles(directory="static", html=True), name="static")

